spring:
  application:
    name: read-data-from-presto
  datasource:
    url: jdbc:presto://8c9a8839-3f7d-4fcf-b523-1bae0b0f592e.co1u05ot0jqujbai8j2g.lakehouse.appdomain.cloud:31389?SSL=true
    username: ibmlhapikey
    password: gUyXpuVk0mdBeSisPrmQJwBPLt3DvGIm1XxA_hGB2GCn
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver
